blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ok-ryoko/turret/discussions
    about: Start a new discussion or join an existing discussion if your query isn’t a bug report
